#!/bin/bash

echo "Installing FlowR addin..."

# Install remotes if missing
Rscript -e "if (!requireNamespace('remotes', quietly = TRUE)) install.packages('remotes', repos='https://cloud.r-project.org')"

# Install the FlowR addin
Rscript -e "remotes::install_github('flowr-analysis/rstudio-addin-flowr@v0.1.2')"
