#!/bin/bash

echo "Checking if FlowR should be installed..."

if [ "$ENABLE_FLOWR" = "true" ]; then
  echo "ENABLE_FLOWR is set to true — installing FlowR..."
  Rscript -e "remotes::install_github('flowr-analysis/rstudio-addin-flowr@v0.1.2')"
else
  echo "ENABLE_FLOWR not set or not 'true' — skipping FlowR installation."
fi
